export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
    PING: "/auth/ping",
  },
  USERS: {
    ME: "/users/me",
    BY_ID: (id: number | string) => `/users/${id}`,
  },
  PARTNERS: {
    BASE: "/partners",
    INVITE: "/partners/invite",
    ACCEPT: "/partners/accept",
    REJECT: "/partners/reject",
    CONNECTION: "/partners/connection",
    ACTIVITY: "/partners/activity",
  },
  HABITS: {
    BASE: "/habits",
    BY_ID: (id: number | string) => `/habits/${id}`,
    COMPLETE: (id: number | string) => `/habits/${id}/complete`,
    HISTORY: (id: number | string) => `/habits/${id}/history`,
  },
  GOALS: {
    BASE: "/goals",
    BY_ID: (id: number | string) => `/goals/${id}`,
    PERSONAL: "/goals/personal",
    SHARED: "/goals/shared",
    COMPLETED: "/goals/completed",
    PARTNER: "/goals/partner",
    PROGRESS: (id: number | string) => `/goals/${id}/progress`,
  },
  ACTIVITY: {
    BASE: "/activity",
    ME: "/activity/me",
    PARTNER: "/activity/partner",
    REACT: (id: number | string) => `/activity/${id}/react`,
    REACT_EMOJI: (id: number | string, emoji: string) => `/activity/${id}/react/${encodeURIComponent(emoji)}`,
  },
  COMPANION: {
    BASE: "/companion",
    CHOOSE: "/companion/choose",
    PARTNER: "/companion/partner",
    HISTORY: "/companion/history",
    INTERACT: "/companion/interact",
  },
  SURPRISES: {
    BASE: "/surprises",
    RECEIVED: "/surprises/received",
    SENT: "/surprises/sent",
    SCHEDULED: "/surprises/scheduled",
    BY_ID: (id: number | string) => `/surprises/${id}`,
    OPEN: (id: number | string) => `/surprises/${id}/open`,
    SEND_DRAFT: (id: number | string) => `/surprises/${id}/send`,
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    READ: (id: number | string) => `/notifications/${id}/read`,
    READ_ALL: "/notifications/read-all",
  },
  ANALYTICS: {
    BASE: "/analytics",
    PARTNER: "/analytics/partner",
    DAILY: "/analytics/daily-completion",
    WEEKLY: "/analytics/weekly-completion",
    MONTHLY: "/analytics/monthly-completion",
    HABIT_CONSISTENCY: "/analytics/habit-consistency",
    GOAL_PROGRESS: "/analytics/goal-progress",
    STREAK_HISTORY: "/analytics/streak-history",
    XP_GROWTH: "/analytics/xp-growth",
  },
} as const;
